### ISSUE TITLE
Exception is thrown when Project ID has hyphen (-) 

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1073]
**Describe the bug**
In my testing, I came across the below exception when the project ID has a hyphen 
Ex: ID as ce768482-b2d7-4364-ad95-c1fa9f700ce4

[dotnet data provider]
Exception while handling message: System.ArgumentException: String must contain only hexadecimal characters: ce768482-b2d7-4364-ad95-c1fa9f700ce4
   at PtxUtils.StringUtils.HexToByteArr(String hexStr)
   at Paratext.Data.HexId..ctor(String hexId)
   at Paratext.Data.HexId.FromStr(String hexStr)
   at Paranext.DataProvider.Projects.LocalParatextProjects.GetParatextProject(String projectId) in C:\Repos\paranext-core\c-sharp\Projects\LocalParatextProjects.cs:line 118
   at Paranext.DataProvider.Checks.CheckRunner.GetOrCreateDataSource(String projectId) in C:\Repos\paranext-core\c-sharp\Checks\CheckRunner.cs:line 307
   at Paranext.DataProvider.Checks.CheckRunner.EnableCheck(String checkId, String projectId) in C:\Repos\paranext-core\c-sharp\Checks\CheckRunner.cs:line 170
   at Paranext.DataProvider.Checks.CheckRunner.HandleRequest(String functionName, JsonArray args) in C:\Repos\paranext-core\c-sharp\Checks\CheckRunner.cs:line 92
   at Paranext.DataProvider.NetworkObjects.DataProvider.FunctionHandler(JsonElement request) in C:\Repos\paranext-core\c-sharp\NetworkObjects\DataProvider.cs:line 91
   at Paranext.DataProvider.MessageHandlers.MessageHandlerRequestByRequestType.HandleMessage(Message message)+MoveNext() in C:\Repos\paranext-core\c-sharp\MessageHandlers\MessageHandlerRequestByRequestType.cs:line 47
   at Paranext.DataProvider.MessageTransports.PapiClient.HandleIncomingMessage(Message message) in C:\Repos\paranext-core\c-sharp\MessageTransports\PapiClient.cs:line 545

**Expected behavior**
Feedback from TJ:  Should handle the exception more gracefully

**Comment by tjcouch-sil** [comment]
@roopa0222  do you remember if this crashes things or makes them fail? Does it make some parts show up but not do anything? Or does it just not load that one particular project into the open project dialog?

**Comment by roopa0222** [comment]
@tjcouch-sil, I had this error when I had `Helloworld` PDP, which has settings validation in the settings file (generated ID with hyphens ). Then, when I tried to update a regular project (zzz), I had an issue. It failed to bring up the application. 

Sorry, I should have added more info. I will reproduce it, but so much code has changed. 
If I can I will update here with more details.
