### ISSUE TITLE
Projects don't open properly on macOS

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#1177]
**Describe the bug**
[From Steve on Discord](https://discord.com/channels/1064938364597436416/1064943951389405204/1288516407138582540):
when I try opening either the Scripture editor or the Resource viewer in Platform.bible, nothing happens. 

**Expected behavior**
Things work properly

Steve's log file:
[message (2).txt](https://github.com/user-attachments/files/17170426/message.2.txt)

Notable exception:
[dotnet data provider error]
System.IO.FileLoadException: Can't load ICU library (version 74)
File name: 'icuuc'
   at Icu.NativeMethods.LoadIcuLibrary(String libraryName)
   at Icu.NativeMethods.get_IcuCommonLibHandle()
   at Icu.NativeMethods.u_init(ErrorCode& errorCode)
   at Icu.Wrapper.Init()
   at Paratext.Data.Languages.WritingSystemRepository.Initialize(IWritingSystemRepository`1 repository)
   at Paratext.Data.ParatextData.Initialize(String settingsDir, Boolean initializePt7Data)
   at Paranext.DataProvider.ParatextUtils.ParatextGlobals.SetParatextDataPath(String dataFolderPath) in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/ParatextUtils/ParatextGlobals.cs:line 45
   at Paranext.DataProvider.ParatextUtils.ParatextGlobals.Initialize(String dataFolderPath) in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/ParatextUtils/ParatextGlobals.cs:line 38
   at Paranext.DataProvider.Projects.LocalParatextProjects.Initialize(Boolean shouldIncludePT9ProjectsOnWindows) in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/Projects/LocalParatextProjects.cs:line 68
   at Paranext.DataProvider.Projects.ParatextProjectDataProviderFactory.StartFactory() in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/Projects/ParatextProjectDataProviderFactory.cs:line 37
   at Paranext.DataProvider.Projects.ProjectDataProviderFactory.Initialize() in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/Projects/ProjectDataProviderFactory.cs:line 27
   at Paranext.DataProvider.Program.Main() in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/Program.cs:line 44
   at Paranext.DataProvider.Program.Main() in /Users/runner/work/paratext-10-studio/paratext-10-studio/temp-build/paranext-core/c-sharp/Program.cs:line 67
   at Paranext.DataProvider.Program.<Main>()
[/dotnet data provider error]

It knows that version 74 is there, but it failed to load for some reason. We should probably pick up [this change from icu.net](https://github.com/sillsdev/icu-dotnet/commit/34b3bf6c05afd55ca6c5e6e6c05330d7ad9ea41a), which may require a new release, and then try again. There isn't enough information in the existing exception message, but we can get more from icu.net with this PR.

**Comment by lyonsil** [comment]
Not sure if this is the same problem: https://discord.com/channels/1064938364597436416/1064943951389405204/1289309650675699716
We're trying to get a log file to get more information

**Comment by tjcouch-sil** [comment]
Note: Steve is using the Intel version. However, Fletcher seems to be having the same issue on Apple silicon

**Comment by lyonsil** [comment]
With more logging enabled, it seems that the arm64 version of libicuuc is getting packaged with the x64/universal application.

**Comment by lyonsil** [comment]
To see what type of `dylib` is installed on a computer, run:
```
file /Applications/Platform.Bible.app/Contents/Resources/dotnet/libicuuc.74.dylib
```
The output will look something like:
```
Mach-O 64-bit dynamically linked shared library arm64
```
