### ISSUE TITLE
Extension can break app

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#1295]
**Describe the bug**
When an extension works improperly it can break the whole app.
Maybe here it is caused by a bad d.ts. file provided, not sure.

- similar to https://github.com/paranext/paranext-core/issues/1149

![image](https://github.com/user-attachments/assets/9ae6f626-af33-4be2-b59a-5f85eb9d2bc2)

> [start:core] [1] 10:10:36 [extension host warning] 10:10:36.372 > Extension webViewer specified its type declaration file was at src/types/web-viewer.d.ts, but this path does not seem to exist. Trying other options [at C:\code\paranext-core\src\extension-host\services\extension.service.ts:503:18]

> [start:core] [1] 10:10:43
[start:core] [1] [extension host error]
[start:core] [1] C:\code\paranext-core\src\shared\services\network.service.ts:210
[start:core] [1]   if (!response.success) throw new Error(response.errorMessage);
[start:core] [1]                                ^
[start:core] [1] [/extension host error]
[start:core] [1] 10:10:43
[start:core] [1] [extension host error]
[start:core] [1] Error: requestType command:webViewer.openWiBiLex already has a remote handler registered
[start:core] [1]     at requestUnsafe (C:\code\paranext-core\src\shared\services\network.service.ts:210:32)
[start:core] [1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[start:core] [1]     at async registerRequestHandlerUnsafe (C:\code\paranext-core\src\shared\services\network.service.ts:321:5)
[start:core] [1] [/extension host error]
[start:core] [1] 10:10:43 Client 1 disconnected! Unregistering extensionAsset:getExtensionAsset, object:platform.menuDataServiceDataProvider-data.get, object:platform.menuDataServiceDataProvider-data.function, object:ProjectSettingsService.get,
...

> [start:core] [1] 10:10:57 [dotnet data provider error] Request failed: "Request: object:platform.settingsServiceDataProvider-data.function (2) from 2" with error message "No handler was found to process the request of type object:platform.settingsServiceDataProvider-data.function"

> [start:core] [1] 10:10:59 Could not get platform-bible-toolbar menu data! Error: Menu data service undefined [at transport C:\code\paranext-core\.erb\dll\main.bundle.dev.js:4207:15]

Logs
[logs.txt](https://github.com/user-attachments/files/17714063/logs.txt)

**Expected behavior**
In case of errors in the extension, the app should continue to run and only trow out the extension's functionality.

**Environment**
Dev, Windows

**Comment by Sebastian-ubs** [comment]
Fatal: when the extension breaks platform you cannot disable the app through the marketplace, because it won't run

**Comment by Sebastian-ubs** [comment]
Another way to crash the whole app is the following - not sure why

 ```
papi.webViews.getWebView("myExtension.webView");
```

  > [start:core] [1] 11:35:18
[start:core] [1] [extension host error]
[start:core] [1] C:\code\paranext-core\src\shared\services\network.service.ts:210
[start:core] [1]   if (!response.success) throw new Error(response.errorMessage);
[start:core] [1]                                ^
[start:core] [1] [/extension host error]
[start:core] [1] 11:35:18
[start:core] [1] [extension host error]
[start:core] [1] Error: Input must be a string
[start:core] [1]     at requestUnsafe (C:\code\paranext-core\src\shared\services\network.service.ts:210:32)
[start:core] [1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[start:core] [1] [/extension host error]
[start:core] [1] 11:35:18 Client 1 disconnected! Unregistering
[...]

> [start:core] [1] 11:35:18 [extension host] [nodemon] app crashed - waiting for file changes before starting...

(but I have not seen the app to recover from this state. When removing the bad code, the app won't come up again, so the whole app has to be shut down and started fresh)
