### ISSUE TITLE
Invalid locale on Language on User Settings can cause application to crash

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1297]
**Describe the bug**
On the Paranext core edit the Platform Settings > Interface Language to 'temp'. The UI accepts the value and the settings.json is updated.
Now, you can restart the application if it crashes. You can start the application by editing the invalid entry or deleting the settings.json file. 

**To Reproduce**

1. on the main PB menu click on `Settings`
2. Confirm that User Settings dialog appears
3. Click on the `Platform Settings`  tab
4. Enter `temp` value in the `Interface Language`
5. Confirm that settings.json is updated without any issues with 
```
{"platform.verseRef":{"bookNum":5,"chapterNum":5,"verseNum":5},"platform.interfaceLanguage":["temp"]}
```
6. Now restart the application. Notice that app crashes 
The below error is found on the log.
[2024-11-12 15:07:54.106] [error] [extension host error] 15:07:54.104 > RangeError: Incorrect locale information provided [at C:\Repos\paranext-core\src\extension-host\extension-host.ts:57:12]
[2024-11-12 15:07:54.104] [error] RangeError: Incorrect locale information provided [at C:\Repos\paranext-core\src\extension-host\extension-host.ts:57:12]
[2024-11-12 15:07:54.111] [error] 
[extension host error]
C:\Repos\paranext-core\src\shared\utils\localized-strings-document-combiner.ts:85
        ? localizedStringData.localizedStrings?.[Intl.getCanonicalLocales(locale)[0]]
                                                      ^
[/extension host error]
[2024-11-12 15:07:54.113] [error] 
[extension host error]
RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at LocalizedStringsDocumentCombiner.getLocalizedStringData (C:\Repos\paranext-core\src\shared\utils\localized-strings-document-combiner.ts:85:55)
    at moveToFirstLanguageWithData (C:\Repos\paranext-core\src\extension-host\services\localization.service-host.ts:151:40)
    at async LocalizationDataProviderEngine.getLocalizedStrings (C:\Repos\paranext-core\src\extension-host\services\localization.service-host.ts:283:5)
    at async localizeColumns (C:\Repos\paranext-core\src\shared\utils\menu-document-combiner.ts:166:22)
    at async Promise.all (index 0)
    at async C:\Repos\paranext-core\src\shared\utils\menu-document-combiner.ts:266:9
[/extension host error]

**Expected behavior**
Need to prevent the application from entering an invalid locale and prevent crashing.

Note: Main.log is attached.
![Screenshot 2024-11-12 151835](https://github.com/user-attachments/assets/348b73f5-d66e-440a-8b1f-d5f0bfdd9300)

[main_InvalidLocaleError.log](https://github.com/user-attachments/files/17722459/main_InvalidLocaleError.log)

**Comment by tombogle** [comment]
When the work done for #1250 is merged, this can probably be closed as no-longer-relevant since it should be impossible. (It still _might_ make sense to consider putting in actual validation since maybe we can't/shouldn't completely rely on the UI to prevent bogus data.

**Comment by Sebastian-ubs** [comment]
#1250 is merged. Is this still relevant? @roopa0222
