### ISSUE TITLE
Support Homebrew builds on macOS

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#1311]
**User Story**
As a macOS user, I want install Paratext 10 Studio and Platform.Bible using Homebrew so that I can more easily do advanced things (e.g., run with command line arguments, programmatically update versions, etc.).

**Description**
@merchako suggested that getting Paratext and Platform using Homebrew would be nice for some users.

A few things to note:
- We need to pick which types of builds (Apple silicon, universal, or Intel silicon) to produce.
- We need to pick which OSes to support. I assume we'd be looking at binary builds, so we'll need matching build machines to support that.
- We might need to make sure that Homebrew's ICU libraries have not been installed as we had problems with those. We distribute the ICU libraries from MacPorts instead.

**Comment by merchako** [comment]
[Electron v33+](https://www.electronjs.org/blog/electron-33-0) no longer supports [macOS 10.15 Catalina and lower](https://en.wikipedia.org/wiki/MacOS_version_history#Releases), so we're not going to help our users any by supporting those versions with ICU. 

It seems fine to make one macOS build: [universal](https://github.com/electron/universal). 

> A Universal app is just the x64 app and the arm64 app glued together into a single application. It's twice as big because it contains two apps in one. Twice as big should be fine at this time since our users will be early adopters (and developers).

How might I learn more about what went wrong with the Homebrew ICU libraries?

**Comment by lyonsil** [comment]
@merchako I don't remember the details at this point, and the person who got things working using MacPorts was a volunteer who is no longer spending time on the project. Regardless, we have more logging in the icu.net library now that should provide more details than we had previously about why library loading fails at runtime. This is a very recent addition that is very useful on macOS in particular for these sorts of things.

If you want to try to get this working with Homebrew libraries now, you'll probably need to update this from `ParanextDataProvider.csproj`:
```
  <!--
    This assumes that icu4c libs are installed under "/opt/local/lib" on macOS. This is the default
    location for libs that MacPorts installs. If we need to start bundling icu4c libs from
    somewhere other than "/opt/local/lib", this path and some other paths in the build scripts will
    need to be updated. We have to bundle the icu4c libs somehow unless macOS starts to include them
    by default.
    -->
  <ItemGroup>
    <Content Include="/opt/local/lib/libicu*.??.dylib" Exclude="/opt/local/lib/libicutest*.dylib;/opt/local/lib/libicutu*.dylib" Condition="$([MSBuild]::IsOsPlatform('macOS'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```
I don't remember where Homebrew installs its libs. MacPorts installs them under `/opt/local/lib`.

In addition, for GitHub Actions to build using Homebrew there are a number of other changes we'd need to make:
1) Find or create a way to install Homebrew on GitHub build images. Here is what we do for MacPorts:
```
      - name: Install MacPorts
        if: ${{ matrix.os == 'macos-latest' }}
        uses: melusina-org/setup-macports@v1
```
2) Install the universal libs from Homebrew onto the build images. Here is what we do for MacPorts:
```
      - name: Install icu4c on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sudo port -v install icu @74.2_0 +universal
```
3) Unless the Homebrew icu libraries are built a lot differently than the MacPorts ones, update the loader paths that are embedded inside of the icu libraries so that we don't run into problems with the libraries not "seeing" each other. Here is what we do for MacPorts:
```
      - name: Install loader tools on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sudo port -v install ld64

      - name: Fixup loader paths for icu4c
        if: ${{ matrix.os == 'macos-latest' }}
        # LIB_DEPENDENCIES are of the form "<ICU lib short name> <dependency as ICU lib short name>"
        # For example, libicuuc (shortened to "uc") depends on libicudata (shortened to "data")
        # Dependencies can be seen by running "dyld_info -dependents /path/to/something.dylib"
        run: |
          ICU_VERSION=74
          LIB_DEPENDENCIES="
          i18n data
          i18n uc
          io data
          io i18n
          io uc
          uc data
          "
          LIB_DEPENDENCIES=$(echo "$LIB_DEPENDENCIES" | sed '/^$/d')
          while IFS= read -r line; do
            set -- $line
            sudo install_name_tool -change "/opt/local/lib/libicu$2.$ICU_VERSION.dylib" "@loader_path/libicu$2.$ICU_VERSION.dylib" "/opt/local/lib/libicu$1.$ICU_VERSION.dylib"
          done <<< "$LIB_DEPENDENCIES"
```

These steps are part of the `publish.yml`, `package-main.yml`, and `test.yml` GitHub workflows.

Feel free to reach out with questions.

**Comment by chrisvire** [comment]
@lyonsil I am trying to help with codesigning and notarization.  I use Homebrew and it is a very bad idea to combine Homebrew and MacPorts.  

For right now, I am just trying to do a local build so that I can work on the configuration needed for GitHub Actions. When I run `npm start`, I get a failure about copying ICU library.

```
[1] 09:42:48 [dotnet data provider error] Unhandled exception.
[1] 09:42:48
[1] [dotnet data provider error]
[1] System.IO.FileLoadException: Can't load ICU library (version 0)
[1] File name: 'icuuc'
[1]    at Icu.NativeMethods.LoadIcuLibrary(String libraryName)
[1]    at Icu.NativeMethods.get_IcuCommonLibHandle()
[1]    at Icu.NativeMethods.u_init(ErrorCode& errorCode)
[1]    at Icu.Wrapper.Init()
[1]    at Paratext.Data.Languages.WritingSystemRepository.Initialize(IWritingSystemRepository`1 repository)
[1]    at Paratext.Data.ParatextData.Initialize(String settingsDir, Boolean initializePt7Data)
[1]    at Paranext.DataProvider.ParatextUtils.ParatextGlobals.SetParatextDataPath(String dataFolderPath) in /Users/chrish/codereview/paranext-core/c-sharp/ParatextUtils/ParatextGlobals.cs:line 48
[1]    at Paranext.DataProvider.ParatextUtils.ParatextGlobals.Initialize(String dataFolderPath) in /Users/chrish/codereview/paranext-core/c-sharp/ParatextUtils/ParatextGlobals.cs:line 41
[1]    at Paranext.DataProvider.Projects.LocalParatextProjects.Initialize(Boolean shouldIncludePT9ProjectsOnWindows) in /Users/chrish/codereview/paranext-core/c-sharp/Projects/LocalParatextProjects.cs:line 81
[1]    at Paranext.DataProvider.Projects.ParatextProjectDataProviderFactory.StartFactoryAsync() in /Users/chrish/codereview/paranext-core/c-sharp/Projects/ParatextProjectDataProviderFactory.cs:line 36
[1]    at Paranext.DataProvider.Projects.ProjectDataProviderFactory.InitializeAsync() in /Users/chrish/codereview/paranext-core/c-sharp/Projects/ProjectDataProviderFactory.cs:line 27
[1]    at Paranext.DataProvider.Program.Main() in /Users/chrish/codereview/paranext-core/c-sharp/Program.cs:line 46
[1]    at Paranext.DataProvider.Program.Main() in /Users/chrish/codereview/paranext-core/c-sharp/Program.cs:line 75
[1]    at Paranext.DataProvider.Program.<Main>()
[1] [/dotnet data provider error]
[1] 09:42:48 [dotnet data provider error] dotnet watch ❌ Exited with error code 134
```

Here is `brew info icu4c`:

```
brew info icu4c
==> icu4c@76: stable 76.1 (bottled) [keg-only]
C/C++ and Java libraries for Unicode and globalization
https://icu.unicode.org/home
Installed
/opt/homebrew/Cellar/icu4c@76/76.1_1 (277 files, 81MB)
  Poured from bottle using the formulae.brew.sh API on 2024-12-02 at 20:49:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/i/icu4c@76.rb
License: ICU
==> Caveats
icu4c@76 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides libicucore.dylib (but nothing else).

If you need to have icu4c@76 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/icu4c@76/bin:$PATH"' >> /Users/chrish/.bash_profile
  echo 'export PATH="/opt/homebrew/opt/icu4c@76/sbin:$PATH"' >> /Users/chrish/.bash_profile

For compilers to find icu4c@76 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/icu4c@76/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/icu4c@76/include"

For pkg-config to find icu4c@76 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c@76/lib/pkgconfig"
==> Analytics
install: 171,607 (30 days), 528,148 (90 days), 952,560 (365 days)
install-on-request: 3,276 (30 days), 10,042 (90 days), 70,096 (365 days)
build-error: 231 (30 days)
```

I looked at the README.md and I tried assigning:
`export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/opt/icu4c@76/lib"` 

Am I reading it wrong?

I am working with @jolierabideau
