### ISSUE TITLE
Open Project Dialog doesn't open quickly after startup - getMetadata doesn't work

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1396]
**Describe the bug**
Please see https://github.com/paranext/paranext-core/issues/1176#issuecomment-2539221872 - this is a follow-up on that problem

**To Reproduce**

**Expected behavior**

**Comment by roopa0222** [comment]
As part of automation, I install the latest application package for Platform. Bible from Github and run my tests.

1. On the first run the application failed to open the `On the Project > Open Scripture Editor > WEB`
2. I also noticed that the default values from the contribution files (projectSettings.json and settings.json) are not displayed.

I attached the logs from the VM for the test runs (looks like main.old.log is updated lost previous runs info)
Here is the warning from main.log
```
Line 790: [2025-01-03 07:31:34.889] [warn]  <WARN>Did not find any project metadata for {"includeProjectInterfaces":[["platformScripture\\.USX_Book","platformScripture\\.USX_Chapter","platformScripture\\.USX_Verse"]],"excludePdpFactoryIds":["platformScripture\\.scriptureExtenderPdpf"]} after the grace period. If you expected to find projects for these filters, this probably indicates a problem. Maybe not all PDPFs loaded in time. [at C:\Users\ROOPA_~1\AppData\Local\Temp\2qS5KkLAG9mMk17AfMWP9P8mRzH\resources\app.asar\dist\extension-host\extension-host.js:8:90092]
	Line 791: [2025-01-03 07:31:34.897] [warn]  <WARN>Did not find any project metadata for {"includeProjectInterfaces":["platformScripture.USJ_Chapter"]} after the grace period. If you expected to find projects for these filters, this probably indicates a problem. Maybe not all PDPFs loaded in time. [at C:\Users\ROOPA_~1\AppData\Local\Temp\2qS5KkLAG9mMk17AfMWP9P8mRzH\resources\app.asar\dist\extension-host\extension-host.js:8:90092]
	Line 792: [2025-01-03 07:31:34.903] [warn]  <WARN>Open Scripture Editor did not find any projects with matching isEditable! Would show a prompt or something if there were a dialog available to do so [at C:\Users\ROOPA_~1\AppData\Local\Temp\2qS5KkLAG9mMk17AfMWP9P8mRzH\resources\app.asar\dist\extension-host\extension-host.js:8:90092]
```

Platform_03012025_070001.log Console log captured from the automation runs

```
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platformS…ces":["platformScripture.USFM_Verse"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platform.…"projectInterfaces":["platform.base"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platform.…"projectInterfaces":["platform.base"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platformS…aces":["platformScripture.USFM_Book"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platform.…"projectInterfaces":["platform.base"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platform.…"projectInterfaces":["platform.base"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platform.…"projectInterfaces":["platform.base"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 1:498636 Uncaught Error: getMetadataForProject wait for PDPF with platform.…"projectInterfaces":["platform.base"]}} to settle
Error Message: file:///C:/Users/ROOPA_~1/AppData/Local/Temp/2qS5KkLAG9mMk17AfMWP9P8mRzH/resources/app.asar/dist/renderer/renderer.js 74:744389 Uncaught Error: handleMenuCommand error: command: paratextExtensio…"projectInterfaces":["platform.base"]}} to settle
```

Please find the logs for your reference.
Note: All the issues are resolved in the second test run.

[VM_Logs.zip](https://github.com/user-attachments/files/18303795/VM_Logs.zip)
