### ISSUE TITLE
Jest test fail on papi-components

### ISSUE THREAD

**Issue by jolierabideau** [paranext/paranext-core#347]
Running jest tests on papi-components fails for some reason

Added mock of papi-components to [`app.component.test.tsx`](https://github.com/paranext/paranext-core/blob/main/src/__tests__/app.component.test.tsx) and [`paranext-dock-layout.component.test.tsx`](https://github.com/paranext/paranext-core/blob/e7a12aac41c50bbeb654ac632011b53a79bd672d/src/renderer/components/docking/paranext-dock-layout.component.test.ts) for a quick fix. The components should test themselves.

Error from [Test run](https://github.com/paranext/paranext-core/actions/runs/5752208476/job/15592656250):

```
FAIL src/renderer/components/docking/paranext-dock-layout.component.test.ts
  ● Test suite failed to run

    TypeError: Bn is not a function

      2712 |  * LICENSE file in the root directory of this source tree.
      2713 |  */ function _t(e, r) {
    > 2714 |   const n = Bn(e, r);
           |             ^
      2715 |   return process.env.NODE_ENV !== 'production'
      2716 |     ? (...t) => {
      2717 |         const o = typeof e == 'string' ? `"${e}"` : 'component';

      at _t (lib/papi-components/dist/index.cjs.js:2714:13)
      at lib/papi-components/dist/index.cjs.js:3453:17
      at Module.Object.<anonymous> (lib/papi-components/dist/index.cjs.js:4252:8)
      at Object.<anonymous> (src/renderer/testing/test-buttons-panel.component.tsx:2:1)
      at Object.<anonymous> (src/renderer/components/docking/paranext-dock-layout.component.tsx:21:1)
      at Object.<anonymous> (src/renderer/components/docking/paranext-dock-layout.component.test.ts:7:1)

PASS src/extension-host/services/extension-storage.service.test.ts
PASS src/node/utils/crypto-util.test.ts
PASS src/shared/utils/papi-util.test.ts
FAIL src/__tests__/app.component.test.tsx
  ● Test suite failed to run

    TypeError: Bn is not a function

      2712 |  * LICENSE file in the root directory of this source tree.
      2713 |  */ function _t(e, r) {
    > 2714 |   const n = Bn(e, r);
           |             ^
      2715 |   return process.env.NODE_ENV !== 'production'
      2716 |     ? (...t) => {
      2717 |         const o = typeof e == 'string' ? `"${e}"` : 'component';

      at _t (lib/papi-components/dist/index.cjs.js:2714:13)
      at lib/papi-components/dist/index.cjs.js:3453:17
      at Module.Object.<anonymous> (lib/papi-components/dist/index.cjs.js:4252:8)
      at Object.<anonymous> (src/renderer/components/platform-bible-toolbar.tsx:1:1)
      at Object.<anonymous> (src/renderer/app.component.tsx:7:1)
      at Object.<anonymous> (src/__tests__/app.component.test.tsx:5:1)
```

Tracing error leads back to imports of papi-components
line 1 in [`platform-bible-toolbar.tsx`](https://github.com/paranext/paranext-core/blob/e7a12aac41c50bbeb654ac632011b53a79bd672d/src/renderer/components/platform-bible-toolbar.tsx) and line 2 in [`test-buttons-panel.component.tsx`](https://github.com/paranext/paranext-core/blob/e7a12aac41c50bbeb654ac632011b53a79bd672d/src/renderer/testing/test-buttons-panel.component.tsx#L4).

**Comment by jolierabideau** [comment]
@irahopkinson Curious on your thoughts
When investigating this issue it came back to inconsistencies between cjs and es modules. It is resolved when Jest is forced to look at `papi-components/dist/index.es.js` instead of the default `papi-components/dist/index.cjs.js` with `moduleNameMapper`. @tjcouch-sil thought we may need to use a [conditional export](https://nodejs.org/api/packages.html#conditional-exports) but we are unsure of what the downsides to that may be? 

```json
{
     "main": "dist/index.es.js"
     "exports": {
          "import": "dist/index.es.js",
          "require": "dist/index.cjs.js"
     },
}
```

**Comment by irahopkinson** [comment]
@jolierabideau and @tjcouch-sil the usual solution is to split out a `tsconfig.spec.ts` to define how you want to load modules for tests. I hadn't done that because I wanted the tests to load modules the same as code. Not strictly necessary but can catch a certain class of issues. The solution above might work also but beware of the **[Dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard)** mentioned in your **conditional export** link above.
