### ISSUE TITLE
Error Message shows up when the Resource Viewer editor is updated using the RefSelector

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#827]
When a user changes Book or Chapter on the RefSelector on the Platform.Bible main , the Resource viewer content is updated accordingly and it also throws an error on the console.log. 

```
Uncaught (in promise) Error: PtxUtils.SafetyCheckException: User does not have permission to edit (WEB JOS 1).
   at Paratext.Data.ScrText.PutText(Int32 bookNum, Int32 chapterNum, Boolean doMapOut, String usfm, WriteLock textLock)
   at Paranext.DataProvider.Projects.ParatextProjectStorageInterpreter.SetChapterUsx(ScrText scrText, VerseRef vref, String newUsx, WriteLock writeLock) in C:\Repos\paranext-core\c-sharp\Projects\ParatextProjectStorageInterpreter.cs:line 367
    at requestUnsafe (network.service.ts:228:32)
```

**Expected behavior**
TJ Input : Might be good to change it to editable at some point and maybe rename or clarify that it isn't actually the official WEB, but we haven't done that yet.

![Screenshot 2024-04-02 123117](https://github.com/paranext/paranext-core/assets/133702629/21a93089-700b-4bf0-9989-5c62f0511ed6)

**Comment by roopa0222** [comment]
This error was resolved after the TJ restructured the Project Folders.
