### ISSUE TITLE
Error on initializing the Platform.Bible app

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#828]
Below error is logged when PlatForm.Bible is initializing .

[2024-04-02 13:27:24.448] [info]  
[dotnet data provider]
Request type "object:platform.paratextFolders-ParatextStandard-psi-data.get" successfully registered with the server
Registering handler for request type object:platform.paratextFolders-ParatextStandard-psi-data.function...
[/dotnet data provider]
[2024-04-02 13:27:24.449] [info]  [dotnet data provider] Request type "object:platform.paratextFolders-ParatextStandard-psi-data.function" successfully registered with the server
[2024-04-02 13:27:24.456] [info]  [dotnet data provider] Adding Paratext project in map: 32664DC3288A28DF2E2BB75DED887FC8F17A15FB = C:\Users\rupa_\.platform.bible\projects\WEB_32664dc3288a28df2e2bb75ded887fc8f17a15fb\project\paratext
[2024-04-02 13:27:24.644] [info]  
[dotnet data provider]
Failed to load project for [C:\Users\rupa_\.platform.bible\projects\WEB_32664dc3288a28df2e2bb75ded887fc8f17a15fb] = [WEB (32664DC3288A28DF2E2BB75DED887FC8F17A15FB): paratextFolders, ParatextStandard]: System.ArgumentException: WEB - World English Bible USA without Strong's numbers has the same ID as WEB - World English Bible USA without Strong's numbers and was not loaded.
   at Paratext.Data.ScrTextCollection.AddProjectToIndex(ScrText scrText, Boolean checkAlreadyExists)
   at Paratext.Data.ScrTextCollection.AddInternal(ScrText scrText, Boolean skipChangeNotify, Boolean checkAlreadyExists)
   at Paratext.Data.ScrTextCollection.Add(ScrText scrText, Boolean skipChangeNotify, Boolean checkAlreadyExists)
   at Paranext.DataProvider.Projects.LocalParatextProjects.AddProjectToMaps(ProjectDetails projectDetails) in C:\Repos\paranext-core\c-sharp\Projects\LocalParatextProjects.cs:line 163
   at Paranext.DataProvider.Projects.LocalParatextProjects.Initialize() in C:\Repos\paranext-core\c-sharp\Projects\LocalParatextProjects.cs:line 62
[/dotnet data provider]

**Comment by roopa0222** [comment]
This issue was resolved after the restructuring of the project folder. I do not see this error anymore.
