### ISSUE TITLE
KeyNotFoundException is thrown when Project Settings property is used for the first time .

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#904]
**Describe the bug**
In my extension testing I observed that when using useProjectSettings hook the values displayed on the very first load are not coming from the projectSettings.json file, instead coming from the placeholders on the hook initialization.

**To Reproduce**

1. Set up projectSettings.json with the below information
```
  "paranextExtTesting.highlightColor_projectSetting_TC13": {
        "label": "%paranextExtTesting.highlightColor%",
        "description": "%paranextExtTesting.highlightColorDescription%",
        "default": "Aqua",
        "includeProjectTypes": ["ParatextStandard"],
        "excludeProjectTypes": null
      },

```
2. On the webview use the PAPI useProjectSettings hook
```
 const [projectColor, setProjectColorInternally] = useProjectSetting(
    'ParatextStandard',
    'b4c501ad2538989d6fb723518e92408406e232d3',
    'paranextExtTesting.highlightColor_projectSetting_TC13',
    'Green',
  );

```
3. You will find below exception in the main.log and warning in console.log
```
[2024-05-20 17:21:00.390] [warn]  Tried to retrieve data immediately for Setting with selector "paranextExtTesting.highlightColor_projectSetting_TC13", but it threw. Error: System.Collections.Generic.KeyNotFoundException: The given key 'paranextExtTesting.highlightColor_projectSetting_TC13' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Paranext.DataProvider.Projects.ParatextProjectDataProvider.GetProjectSetting(String jsonKey) in C:\Repos\paranext-core\c-sharp\Projects\ParatextProjectDataProvider.cs:line 222
   at Paranext.DataProvider.Projects.ProjectDataProvider.HandleRequest(String functionName, JsonArray args) in C:\Repos\paranext-core\c-sharp\Projects\ProjectDataProvider.cs:line 83

```
4. The UI displays the values from the hook instead of defaults from the projectSettings.json
![Screenshot 2024-05-17_Defaults](https://github.com/paranext/paranext-core/assets/133702629/fbbbf83e-a839-4b17-8412-442a93b49bdc)

**Expected behavior**
Default values from the projectSettings.json should be displayed on the UI

**Comment by tjcouch-sil** [comment]
Matt and I discussed and decided to fix a couple things and leave one other thing for the moment. Hopefully we'll get to the other thing before long:

- (Fixed) Paratext project settings throw instead of getting the default
- (Fixed) Paratext project settings updates don't go out properly
- Paratext project settings don't support numbers or objects #906
