### ISSUE TITLE
Text Collection: Error while clicking around

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#980]
**Describe the bug**
After adding multiple projects, one of them (NLT07) showed empty for Heb 1:1, but shows text after clicking on it.
After clicking some of them (NIV84, ESV16), the text collection ui blanked out and console error appeared on the console
> renderer.js:2 TypeError: Cannot read properties of undefined (reading 'startsWith')
    at index.js:1758:1
    at Array.find (<anonymous>)
    at Us (index.js:1757:1)
    at ue.isValidMarker (index.js:2725:1)
    at _o (index.js:3541:1)
    at index.js:3718:1
    at Array.forEach (<anonymous>)
    at Mt (index.js:3698:1)
    at Object.Al [as serializeEditorState] (index.js:3396:1)
    at index.js:3074:1

On restarting Platform it shows up and then blanks out on its own again.

It does **not** break for: HEBGRK, HBKENG, HPUXK, PCM, NLT07

**To Reproduce**

**Expected behavior**

![grafik](https://github.com/paranext/paranext-core/assets/141921979/2c64a1c7-6564-481b-b219-bc223aacee6d)

**Comment by Sebastian-ubs** [comment]
oh, just disovered that the root cause is an issue in the scripture editor. Will open an issue there...

**Comment by Sebastian-ubs** [comment]
root cause: https://github.com/BiblioNexus-Foundation/scripture-editors/issues/129
